# =============================================================================
# KONFIGURASI BAHASA / LANGUAGE CONFIGURATION
# CyberGuard AI: Enterprise Edition
# =============================================================================

TRANSLATIONS = {
    "id": {
        # Sidebar
        "app_title": "CyberGuard AI",
        "app_subtitle": "Enterprise Edition v1.0",
        "nav_title": "Navigasi",
        "menu_dashboard": "Ringkasan Dashboard",
        "menu_simulation": "Simulasi Langsung",
        "menu_batch": "Analisis Batch",
        "menu_performance": "Performa AI",
        "system_status": "Status Sistem",
        "ai_active": "Model AI Aktif",
        "powered_by": "Didukung oleh Machine Learning",
        "copyright": "© 2024 CyberGuard AI",
        "select_language": "Pilih Bahasa",
        
        # Dashboard
        "dashboard_title": "Ringkasan Dashboard",
        "dashboard_subtitle": "Ringkasan Eksekutif • Metrik Keamanan Real-Time",
        "status_online": "ONLINE",
        "status_label": "Status Sistem",
        "active_monitoring": "Pemantauan Aktif",
        "total_packets": "Total Paket",
        "new_packets": "baru",
        "threat_level": "Level Ancaman",
        "threats": "ancaman",
        "model_accuracy": "Akurasi Model",
        "trained_ready": "Terlatih & Siap",
        "live_traffic": "Volume Lalu Lintas (24j)",
        "traffic_distribution": "Distribusi Klasifikasi Lalu Lintas",
        "normal_traffic": "Lalu Lintas Normal",
        "attack_traffic": "Lalu Lintas Serangan",
        "classification_report": "Laporan Klasifikasi Detail",
        "precision_score": "Skor Presisi",
        "precision_desc": "Akurasi prediksi positif",
        "recall_score": "Skor Recall",
        "recall_desc": "Cakupan positif aktual",
        "f1_score": "Skor F1",
        "f1_desc": "Rata-rata harmonik presisi & recall",
        "threat_low": "RENDAH",
        "threat_moderate": "SEDANG",
        "threat_high": "TINGGI",
        
        # Live Simulation
        "simulation_title": "Simulasi Paket Langsung",
        "simulation_subtitle": "Analisis Log Router Mikrotik • Deteksi Ancaman Real-Time",
        "simulation_instructions": "**Petunjuk**: Masukkan detail paket di bawah untuk mensimulasikan entri log dari router Mikrotik Anda. Model AI akan menganalisis karakteristik paket dan memprediksi apakah itu lalu lintas normal atau serangan potensial.",
        "packet_details": "Detail Paket",
        "protocol_type": "Tipe Protokol",
        "protocol_help": "Protokol lapisan transport yang digunakan",
        "network_service": "Layanan Jaringan",
        "service_help": "Layanan jaringan target",
        "connection_flag": "Flag Koneksi",
        "flag_help": "Flag status koneksi (SF=Normal, S0=Percobaan koneksi, dll.)",
        "duration": "Durasi (detik)",
        "duration_help": "Durasi koneksi dalam detik",
        "source_bytes": "Byte Sumber",
        "src_bytes_help": "Byte yang dikirim dari sumber ke tujuan",
        "dest_bytes": "Byte Tujuan",
        "dst_bytes_help": "Byte yang dikirim dari tujuan ke sumber",
        "connection_count": "Jumlah Koneksi",
        "count_help": "Jumlah koneksi ke host yang sama dalam 2 detik terakhir",
        "service_count": "Jumlah Layanan",
        "srv_count_help": "Jumlah koneksi ke layanan yang sama dalam 2 detik terakhir",
        "scan_packet": "PINDAI PAKET",
        "analyzing": "Menganalisis paket dengan model AI...",
        "analysis_result": "Hasil Analisis",
        "threat_detected": "ANCAMAN TERDETEKSI",
        "potential_intrusion": "Potensi Intrusi Jaringan Teridentifikasi",
        "packet_cleared": "PAKET AMAN",
        "normal_detected": "Lalu Lintas Jaringan Normal Terdeteksi",
        "confidence": "Kepercayaan",
        "normal_prob": "Probabilitas Lalu Lintas Normal",
        "attack_prob": "Probabilitas Serangan",
        "analysis_error": "Kesalahan Analisis",
        "valid_input": "Pastikan semua nilai input valid.",
        
        # Batch Analysis
        "batch_title": "Analisis Log Batch",
        "batch_subtitle": "Unggah Log Mikrotik • Deteksi Ancaman Massal",
        "batch_instructions": "**Petunjuk**: Unggah file CSV yang berisi log lalu lintas jaringan. File harus menyertakan kolom yang dapat dipetakan ke fitur model.",
        "expected_columns": "Kolom CSV yang Diharapkan",
        "column_desc": "File CSV Anda harus berisi kolom berikut:",
        "column": "Kolom",
        "description": "Deskripsi",
        "type": "Tipe",
        "upload_csv": "Unggah File CSV Log",
        "file_success": "File berhasil diunggah! Ditemukan",
        "records": "data",
        "data_preview": "Pratinjau Data yang Diunggah",
        "column_mapping": "Pemetaan Kolom",
        "analyze_logs": "ANALISIS SEMUA LOG",
        "processing": "Memproses analisis batch...",
        "analysis_results": "Hasil Analisis",
        "total_records": "Total Data",
        "threats_detected": "Ancaman Terdeteksi",
        "detection_summary": "Ringkasan Deteksi",
        "detailed_results": "Hasil Detail",
        "download_results": "Unduh Hasil",
        "download_csv": "Unduh Hasil CSV",
        "mapping_error": "Kesalahan Analisis",
        "check_mapping": "Periksa pemetaan kolom dan format data.",
        "file_error": "Kesalahan Membaca File",
        "valid_csv": "Pastikan file dalam format CSV yang valid.",
        
        # AI Performance
        "performance_title": "Performa Model AI",
        "performance_subtitle": "Analisis Ilmiah • Metrik Evaluasi Model",
        "performance_desc": "Bagian ini menyediakan bukti ilmiah efektivitas model AI. Gunakan metrik ini untuk sidang skripsi dan dokumentasi akademik.",
        "performance_overview": "Ringkasan Performa Model",
        "accuracy": "Akurasi",
        "precision": "Presisi",
        "recall": "Recall",
        "confusion_matrix": "Matriks Kebingungan",
        "feature_importance": "Kepentingan Fitur",
        "matrix_interpretation": "Interpretasi Matriks:",
        "true_negatives": "True Negatives (TN)",
        "tn_desc": "Lalu lintas Normal yang teridentifikasi dengan benar",
        "false_positives": "False Positives (FP)",
        "fp_desc": "Lalu lintas Normal yang salah ditandai sebagai Serangan",
        "false_negatives": "False Negatives (FN)",
        "fn_desc": "Lalu lintas Serangan yang salah diklasifikasikan sebagai Normal",
        "true_positives": "True Positives (TP)",
        "tp_desc": "Lalu lintas Serangan yang teridentifikasi dengan benar",
        "key_insights": "Wawasan Utama:",
        "most_important": "Fitur Paling Penting",
        "importance_desc": "Fitur dengan skor kepentingan lebih tinggi memiliki pengaruh lebih besar pada prediksi",
        "analysis_helps": "Analisis ini membantu mengidentifikasi karakteristik jaringan mana yang paling menunjukkan serangan",
        "model_config": "Konfigurasi Model",
        "view_params": "Lihat Parameter Model",
        "academic_refs": "Referensi Akademik",
        "dataset_citation": "Kutipan Dataset:",
        "model_reference": "Referensi Model:",
        
        # Errors
        "init_error": "Menginisialisasi CyberGuard AI...",
        "critical_error": "Kesalahan Kritis: Tidak dapat memuat dataset",
        "ensure_internet": "Pastikan Anda memiliki koneksi internet aktif",
        "ensure_kaggle": "Kredensial Kaggle dikonfigurasi dengan benar",
        "ensure_lib": "Library kagglehub terinstal dengan benar",
        "run_pip": "Jalankan: `pip install kagglehub` dan konfigurasikan kredensial API Kaggle Anda.",
        
        # SOC Monitoring & Simulation Mode (NEW)
        "menu_soc": "SOC Monitoring",
        "operation_mode": "Mode Operasi",
        "enable_simulation": "Aktifkan Mode Simulasi",
        "simulation_help": "Centang untuk menggunakan data dummy (tanpa router fisik)",
        "simulation_active": "Mode Simulasi Aktif",
        "real_mode_warning": "Mode Real - Perlu Router MikroTik",
        "router_config": "Konfigurasi Router",
        "ip_address": "Alamat IP",
        "username": "Nama Pengguna",
        "password": "Kata Sandi",
        "api_port": "Port API",
        "connect_btn": "Hubungkan",
        
        # SOC Dashboard
        "soc_title": "SOC Monitoring",
        "soc_subtitle": "Analisis Lalu Lintas Jaringan Real-Time • Deteksi Ancaman Berbasis AI",
        "auto_refresh": "Auto Refresh",
        "interval": "Interval",
        "seconds": "detik",
        "total_connections": "Total Koneksi",
        "threats_detected_count": "Ancaman Terdeteksi",
        "unique_sources": "Sumber Unik",
        "data_transfer": "Transfer Data",
        "protocol_distribution": "Distribusi Protokol",
        "threat_distribution": "Distribusi Ancaman",
        "live_connection_analysis": "Analisis Koneksi Langsung",
        "filter_label": "Filter",
        "filter_all": "Semua",
        "filter_attacks": "Serangan Saja",
        "filter_normal": "Normal Saja",
        "source": "Sumber",
        "destination": "Tujuan",
        "protocol": "Protokol",
        "bytes": "Byte",
        "count": "Jumlah",
        "status": "Status",
        "active_threat_alerts": "Peringatan Ancaman Aktif",
        "potential_attack": "Potensi Serangan",
        "no_connections": "Tidak ada koneksi untuk ditampilkan",
        "normal": "Normal",
        "attack": "Serangan",
    },
    
    "en": {
        # Sidebar
        "app_title": "CyberGuard AI",
        "app_subtitle": "Enterprise Edition v1.0",
        "nav_title": "Navigation",
        "menu_dashboard": "Dashboard Overview",
        "menu_simulation": "Live Simulation",
        "menu_batch": "Batch Analysis",
        "menu_performance": "AI Performance",
        "system_status": "System Status",
        "ai_active": "AI Model Active",
        "powered_by": "Powered by Machine Learning",
        "copyright": "© 2024 CyberGuard AI",
        "select_language": "Select Language",
        
        # Dashboard
        "dashboard_title": "Dashboard Overview",
        "dashboard_subtitle": "Executive Summary • Real-Time Security Metrics",
        "status_online": "ONLINE",
        "status_label": "System Status",
        "active_monitoring": "Active Monitoring",
        "total_packets": "Total Packets",
        "new_packets": "new",
        "threat_level": "Threat Level",
        "threats": "threats",
        "model_accuracy": "Model Accuracy",
        "trained_ready": "Trained & Ready",
        "live_traffic": "Live Traffic Volume (24h)",
        "traffic_distribution": "Traffic Classification Distribution",
        "normal_traffic": "Normal Traffic",
        "attack_traffic": "Attack Traffic",
        "classification_report": "Detailed Classification Report",
        "precision_score": "Precision Score",
        "precision_desc": "Accuracy of positive predictions",
        "recall_score": "Recall Score",
        "recall_desc": "Coverage of actual positives",
        "f1_score": "F1 Score",
        "f1_desc": "Harmonic mean of precision & recall",
        "threat_low": "LOW",
        "threat_moderate": "MODERATE",
        "threat_high": "HIGH",
        
        # Live Simulation
        "simulation_title": "Live Packet Simulation",
        "simulation_subtitle": "Mikrotik Router Log Analysis • Real-Time Threat Detection",
        "simulation_instructions": "**Instructions**: Enter packet details below to simulate a log entry from your Mikrotik router. The AI model will analyze the packet characteristics and predict if it's normal traffic or a potential attack.",
        "packet_details": "Packet Details",
        "protocol_type": "Protocol Type",
        "protocol_help": "Transport layer protocol used",
        "network_service": "Network Service",
        "service_help": "Target network service",
        "connection_flag": "Connection Flag",
        "flag_help": "Connection status flag (SF=Normal, S0=Connection attempt, etc.)",
        "duration": "Duration (seconds)",
        "duration_help": "Connection duration in seconds",
        "source_bytes": "Source Bytes",
        "src_bytes_help": "Bytes sent from source to destination",
        "dest_bytes": "Destination Bytes",
        "dst_bytes_help": "Bytes sent from destination to source",
        "connection_count": "Connection Count",
        "count_help": "Number of connections to same host in past 2 seconds",
        "service_count": "Service Count",
        "srv_count_help": "Number of connections to same service in past 2 seconds",
        "scan_packet": "SCAN PACKET",
        "analyzing": "Analyzing packet with AI model...",
        "analysis_result": "Analysis Result",
        "threat_detected": "THREAT DETECTED",
        "potential_intrusion": "Potential Network Intrusion Identified",
        "packet_cleared": "PACKET CLEARED",
        "normal_detected": "Normal Network Traffic Detected",
        "confidence": "Confidence",
        "normal_prob": "Normal Traffic Probability",
        "attack_prob": "Attack Probability",
        "analysis_error": "Analysis Error",
        "valid_input": "Please ensure all input values are valid.",
        
        # Batch Analysis
        "batch_title": "Batch Log Analysis",
        "batch_subtitle": "Upload Mikrotik Logs • Bulk Threat Detection",
        "batch_instructions": "**Instructions**: Upload a CSV file containing network traffic logs. The file should include columns that can be mapped to the model's features.",
        "expected_columns": "Expected CSV Columns",
        "column_desc": "Your CSV file should contain the following columns:",
        "column": "Column",
        "description": "Description",
        "type": "Type",
        "upload_csv": "Upload CSV Log File",
        "file_success": "File uploaded successfully! Found",
        "records": "records",
        "data_preview": "Uploaded Data Preview",
        "column_mapping": "Column Mapping",
        "analyze_logs": "ANALYZE ALL LOGS",
        "processing": "Processing batch analysis...",
        "analysis_results": "Analysis Results",
        "total_records": "Total Records",
        "threats_detected": "Threats Detected",
        "detection_summary": "Detection Summary",
        "detailed_results": "Detailed Results",
        "download_results": "Download Results",
        "download_csv": "Download Results CSV",
        "mapping_error": "Analysis Error",
        "check_mapping": "Please check column mappings and data format.",
        "file_error": "File Reading Error",
        "valid_csv": "Please ensure the file is a valid CSV format.",
        
        # AI Performance
        "performance_title": "AI Model Performance",
        "performance_subtitle": "Scientific Analysis • Model Evaluation Metrics",
        "performance_desc": "This section provides scientific proof of the AI model's effectiveness. Use these metrics for thesis defense and academic documentation.",
        "performance_overview": "Model Performance Overview",
        "accuracy": "Accuracy",
        "precision": "Precision",
        "recall": "Recall",
        "confusion_matrix": "Confusion Matrix",
        "feature_importance": "Feature Importance",
        "matrix_interpretation": "Matrix Interpretation:",
        "true_negatives": "True Negatives (TN)",
        "tn_desc": "Correctly identified Normal traffic",
        "false_positives": "False Positives (FP)",
        "fp_desc": "Normal traffic incorrectly flagged as Attack",
        "false_negatives": "False Negatives (FN)",
        "fn_desc": "Attack traffic incorrectly classified as Normal",
        "true_positives": "True Positives (TP)",
        "tp_desc": "Correctly identified Attack traffic",
        "key_insights": "Key Insights:",
        "most_important": "Most Important Feature",
        "importance_desc": "Features with higher importance scores have greater influence on predictions",
        "analysis_helps": "This analysis helps identify which network characteristics are most indicative of attacks",
        "model_config": "Model Configuration",
        "view_params": "View Model Parameters",
        "academic_refs": "Academic References",
        "dataset_citation": "Dataset Citation:",
        "model_reference": "Model Reference:",
        
        # Errors
        "init_error": "Initializing CyberGuard AI...",
        "critical_error": "Critical Error: Unable to load dataset",
        "ensure_internet": "You have an active internet connection",
        "ensure_kaggle": "Kaggle credentials are properly configured",
        "ensure_lib": "The kagglehub library is installed correctly",
        "run_pip": "Run: `pip install kagglehub` and configure your Kaggle API credentials.",
        
        # SOC Monitoring & Simulation Mode (NEW)
        "menu_soc": "SOC Monitoring",
        "operation_mode": "Operation Mode",
        "enable_simulation": "Enable Simulation Mode",
        "simulation_help": "Check to use dummy data (without physical router)",
        "simulation_active": "Simulation Mode Active",
        "real_mode_warning": "Real Mode - MikroTik Router Required",
        "router_config": "Router Configuration",
        "ip_address": "IP Address",
        "username": "Username",
        "password": "Password",
        "api_port": "API Port",
        "connect_btn": "Connect",
        
        # SOC Dashboard
        "soc_title": "SOC Monitoring",
        "soc_subtitle": "Real-Time Network Traffic Analysis • AI-Powered Threat Detection",
        "auto_refresh": "Auto Refresh",
        "interval": "Interval",
        "seconds": "seconds",
        "total_connections": "Total Connections",
        "threats_detected_count": "Threats Detected",
        "unique_sources": "Unique Sources",
        "data_transfer": "Data Transfer",
        "protocol_distribution": "Protocol Distribution",
        "threat_distribution": "Threat Distribution",
        "live_connection_analysis": "Live Connection Analysis",
        "filter_label": "Filter",
        "filter_all": "All",
        "filter_attacks": "Attacks Only",
        "filter_normal": "Normal Only",
        "source": "Source",
        "destination": "Destination",
        "protocol": "Protocol",
        "bytes": "Bytes",
        "count": "Count",
        "status": "Status",
        "active_threat_alerts": "Active Threat Alerts",
        "potential_attack": "Potential Attack",
        "no_connections": "No connections to display",
        "normal": "Normal",
        "attack": "Attack",
    }
}

def get_text(key, lang="id"):
    """Mengambil teks berdasarkan kunci dan bahasa."""
    return TRANSLATIONS.get(lang, TRANSLATIONS["id"]).get(key, key)
